import { CircleDollarSign, Clock3, Plus, Star, Trash2, TrendingUp, Users } from 'lucide-react'
import { useState, type FormEvent } from 'react'
import { ConfirmModal, Modal } from '../components/Modal'
import { useApp } from '../context/AppContext'
import type { Contract, ContractStatus, Platform } from '../types'
import { contractMetrics, netBrl, netHourly, netUsd } from '../utils/calculations'
import { toDateInput } from '../data/roadmap'

const platforms: Platform[] = ['Upwork', '99Freelas', 'LinkedIn', 'Indicação', 'Outra']
const statuses: ContractStatus[] = ['Em negociação', 'Em andamento', 'Entregue', 'Pausado', 'Cancelado']
const emptyContract = (exchangeRate: number): Contract => ({ id: crypto.randomUUID(), project: '', client: '', platform: 'Upwork', service: '', startDate: toDateInput(new Date()), deadline: '', grossUsd: 0, platformFeePercent: 10, exchangeRate, hoursWorked: 0, status: 'Em negociação', rating: null, notes: '' })

function ContractForm({ initial, onClose }: { initial: Contract; onClose: () => void }) {
  const { upsert, notify } = useApp(); const [form, setForm] = useState(initial)
  const set = <K extends keyof Contract>(key: K, value: Contract[K]) => setForm((current) => ({ ...current, [key]: value }))
  const submit = (event: FormEvent) => { event.preventDefault(); upsert('contracts', form); notify('Contrato salvo com sucesso.', 'success'); onClose() }
  return <form className="form-grid" onSubmit={submit}><label>Projeto *<input required value={form.project} onChange={(e) => set('project', e.target.value)} /></label><label>Cliente *<input required value={form.client} onChange={(e) => set('client', e.target.value)} /></label><label>Plataforma<select value={form.platform} onChange={(e) => set('platform', e.target.value as Platform)}>{platforms.map((item) => <option key={item}>{item}</option>)}</select></label><label>Serviço<input value={form.service} onChange={(e) => set('service', e.target.value)} /></label><label>Data de início<input type="date" value={form.startDate} onChange={(e) => set('startDate', e.target.value)} /></label><label>Prazo<input type="date" value={form.deadline} onChange={(e) => set('deadline', e.target.value)} /></label><label>Valor bruto (US$)<input type="number" min="0" step="0.01" value={form.grossUsd} onChange={(e) => set('grossUsd', Number(e.target.value))} /></label><label>Taxa da plataforma (%)<input type="number" min="0" max="100" step="0.1" value={form.platformFeePercent} onChange={(e) => set('platformFeePercent', Number(e.target.value))} /></label><label>Cotação manual do dólar<input type="number" min="0" step="0.01" value={form.exchangeRate} onChange={(e) => set('exchangeRate', Number(e.target.value))} /></label><label>Horas trabalhadas<input type="number" min="0" step="0.25" value={form.hoursWorked} onChange={(e) => set('hoursWorked', Number(e.target.value))} /></label><label>Status<select value={form.status} onChange={(e) => set('status', e.target.value as ContractStatus)}>{statuses.map((item) => <option key={item}>{item}</option>)}</select></label><label>Avaliação recebida<input type="number" min="1" max="5" step="0.1" value={form.rating ?? ''} onChange={(e) => set('rating', e.target.value ? Number(e.target.value) : null)} /></label><div className="calculation-preview wide"><span>Líquido: <strong>US$ {netUsd(form).toFixed(2)}</strong></span><span>Em reais: <strong>R$ {netBrl(form).toFixed(2)}</strong></span><span>Por hora: <strong>US$ {netHourly(form).toFixed(2)}</strong></span></div><label className="wide">Observações<textarea value={form.notes} onChange={(e) => set('notes', e.target.value)} /></label><div className="form-actions wide"><button type="button" className="button secondary" onClick={onClose}>Cancelar</button><button className="button primary">Salvar contrato</button></div></form>
}

export function ContractsPage() {
  const { data, remove, notify } = useApp(); const [editing, setEditing] = useState<Contract | null>(null); const [deleting, setDeleting] = useState<Contract | null>(null)
  const metrics = contractMetrics(data.contracts)
  const cards = [{ label: 'Receita líquida', value: `US$ ${metrics.revenueUsd.toFixed(2)}`, icon: CircleDollarSign }, { label: 'Receita do mês', value: `US$ ${metrics.monthlyRevenue.toFixed(2)}`, icon: TrendingUp }, { label: 'Em reais', value: `R$ ${metrics.revenueBrl.toFixed(2)}`, icon: TrendingUp }, { label: 'Média por projeto', value: `US$ ${metrics.averageProject.toFixed(2)}`, icon: CircleDollarSign }, { label: 'Líquido por hora', value: `US$ ${metrics.averageHourly.toFixed(2)}`, icon: Clock3 }, { label: 'Clientes', value: metrics.clients, icon: Users }, { label: 'Recorrentes', value: metrics.recurringClients, icon: Star }]
  return <div><section className="page-intro"><div><span className="kicker">Saúde financeira</span><h2>Clientes e ganhos</h2><p>Valores líquidos, horas e relacionamentos em um só lugar.</p></div><button className="button primary" onClick={() => setEditing(emptyContract(data.settings.defaultExchangeRate))}><Plus size={17} /> Novo contrato</button></section><section className="stats-grid contract-stats">{cards.map(({ label, value, icon: Icon }) => <article className="stat-card" key={label}><div className="stat-icon green"><Icon size={19} /></div><div><span>{label}</span><strong>{value}</strong></div></article>)}</section>
    {data.contracts.length === 0 ? <div className="empty-state"><CircleDollarSign size={40} /><h3>Registre seu primeiro contrato</h3><p>Os ganhos líquidos e valores por hora serão calculados automaticamente.</p><button className="button primary" onClick={() => setEditing(emptyContract(data.settings.defaultExchangeRate))}><Plus size={17} /> Adicionar contrato</button></div> : <div className="contract-grid">{data.contracts.map((item) => <article className="card contract-card" key={item.id}><header><div><span>{item.platform}</span><h3>{item.project}</h3><p>{item.client}</p></div><span className={`status-pill contract-${item.status.toLowerCase().replaceAll(' ', '-')}`}>{item.status}</span></header><div className="contract-values"><div><span>Valor líquido</span><strong>US$ {netUsd(item).toFixed(2)}</strong><small>R$ {netBrl(item).toFixed(2)}</small></div><div><span>Por hora</span><strong>US$ {netHourly(item).toFixed(2)}</strong><small>{item.hoursWorked}h registradas</small></div></div><footer><button className="text-button" onClick={() => setEditing(item)}>Editar detalhes</button><button className="icon-button danger-icon" onClick={() => data.settings.confirmBeforeDelete ? setDeleting(item) : remove('contracts', item.id)} aria-label="Excluir contrato"><Trash2 size={16} /></button></footer></article>)}</div>}
    {editing && <Modal title={data.contracts.some((item) => item.id === editing.id) ? 'Editar contrato' : 'Novo contrato'} onClose={() => setEditing(null)} size="large"><ContractForm initial={editing} onClose={() => setEditing(null)} /></Modal>}{deleting && <ConfirmModal title="Excluir contrato?" message={`Os dados de “${deleting.project}” serão removidos.`} danger onClose={() => setDeleting(null)} onConfirm={() => { remove('contracts', deleting.id); notify('Contrato excluído.') }} />}</div>
}
