import { ArrowUpDown, BriefcaseBusiness, Copy, ExternalLink, Plus, Search, Send, Trash2, UserRoundCheck } from 'lucide-react'
import { useMemo, useState, type FormEvent } from 'react'
import { ConfirmModal, Modal } from '../components/Modal'
import { useApp } from '../context/AppContext'
import type { Platform, Proposal, ProposalStatus } from '../types'
import { proposalMetrics } from '../utils/calculations'
import { toDateInput } from '../data/roadmap'

const platforms: Platform[] = ['Upwork', '99Freelas', 'LinkedIn', 'Indicação', 'Outra']
const statuses: ProposalStatus[] = ['Salva', 'Enviada', 'Visualizada', 'Entrevista', 'Contratado', 'Recusada', 'Ignorada']
const dateNow = () => toDateInput(new Date())
const emptyProposal = (): Proposal => ({ id: crypto.randomUUID(), date: dateNow(), platform: 'Upwork', projectName: '', clientName: '', serviceType: '', budgetUsd: 0, connects: 0, url: '', status: 'Salva', deadline: '', estimatedHours: 0, estimatedHourlyRate: 0, nextStep: '', notes: '', followUpDate: '' })

function ProposalForm({ initial, onClose }: { initial: Proposal; onClose: () => void }) {
  const { upsert, notify } = useApp()
  const [form, setForm] = useState(initial)
  const set = <K extends keyof Proposal>(key: K, value: Proposal[K]) => setForm((current) => ({ ...current, [key]: value, ...(key === 'budgetUsd' || key === 'estimatedHours' ? { estimatedHourlyRate: key === 'budgetUsd' ? Number(value) / (current.estimatedHours || 1) : current.budgetUsd / (Number(value) || 1) } : {}) }))
  const submit = (event: FormEvent) => { event.preventDefault(); if (!form.projectName.trim()) return; upsert('proposals', form); notify('Proposta salva com sucesso.', 'success'); onClose() }
  return <form onSubmit={submit} className="form-grid"><label className="wide">Projeto *<input required value={form.projectName} onChange={(e) => set('projectName', e.target.value)} /></label><label>Cliente<input value={form.clientName} onChange={(e) => set('clientName', e.target.value)} /></label><label>Plataforma<select value={form.platform} onChange={(e) => set('platform', e.target.value as Platform)}>{platforms.map((item) => <option key={item}>{item}</option>)}</select></label><label>Data<input type="date" value={form.date} onChange={(e) => set('date', e.target.value)} /></label><label>Status<select value={form.status} onChange={(e) => set('status', e.target.value as ProposalStatus)}>{statuses.map((item) => <option key={item}>{item}</option>)}</select></label><label className="wide">Tipo de serviço<input value={form.serviceType} onChange={(e) => set('serviceType', e.target.value)} /></label><label>Orçamento (US$)<input type="number" min="0" step="0.01" value={form.budgetUsd} onChange={(e) => set('budgetUsd', Number(e.target.value))} /></label><label>Connects<input type="number" min="0" value={form.connects} onChange={(e) => set('connects', Number(e.target.value))} /></label><label>Horas estimadas<input type="number" min="0" step="0.5" value={form.estimatedHours} onChange={(e) => set('estimatedHours', Number(e.target.value))} /></label><label>Estimativa por hora<input readOnly value={`US$ ${form.estimatedHourlyRate.toFixed(2)}`} /></label><label>Prazo<input type="date" value={form.deadline} onChange={(e) => set('deadline', e.target.value)} /></label><label>Acompanhar em<input type="date" value={form.followUpDate} onChange={(e) => set('followUpDate', e.target.value)} /></label><label className="wide">Link do anúncio<input type="url" placeholder="https://" value={form.url} onChange={(e) => set('url', e.target.value)} /></label><label className="wide">Próximo passo<input value={form.nextStep} onChange={(e) => set('nextStep', e.target.value)} /></label><label className="wide">Observações<textarea value={form.notes} onChange={(e) => set('notes', e.target.value)} /></label><div className="form-actions wide"><button type="button" className="button secondary" onClick={onClose}>Cancelar</button><button className="button primary">Salvar proposta</button></div></form>
}

export function ProposalsPage() {
  const { data, upsert, remove, notify } = useApp()
  const [editing, setEditing] = useState<Proposal | null>(null)
  const [deleting, setDeleting] = useState<Proposal | null>(null)
  const [search, setSearch] = useState('')
  const [status, setStatus] = useState('')
  const [platform, setPlatform] = useState('')
  const [sortDesc, setSortDesc] = useState(true)
  const metrics = proposalMetrics(data.proposals)
  const list = useMemo(() => data.proposals.filter((item) => (!search || `${item.projectName} ${item.clientName} ${item.serviceType}`.toLowerCase().includes(search.toLowerCase())) && (!status || item.status === status) && (!platform || item.platform === platform)).sort((a, b) => sortDesc ? b.date.localeCompare(a.date) : a.date.localeCompare(b.date)), [data.proposals, search, status, platform, sortDesc])
  const duplicate = (item: Proposal) => { upsert('proposals', { ...item, id: crypto.randomUUID(), projectName: `${item.projectName} (cópia)`, date: dateNow(), status: 'Salva' }); notify('Proposta duplicada.', 'success') }
  return <div>
    <section className="page-intro"><div><span className="kicker">Pipeline comercial</span><h2>Propostas</h2><p>Acompanhe cada oportunidade e saiba quando fazer contato.</p></div><button className="button primary" onClick={() => setEditing(emptyProposal())}><Plus size={17} /> Nova proposta</button></section>
    <section className="metric-strip"><div><Send /><span>Enviadas<strong>{metrics.sent}</strong></span></div><div><UserRoundCheck /><span>Taxa de entrevista<strong>{metrics.interviewRate.toFixed(0)}%</strong></span></div><div><BriefcaseBusiness /><span>Taxa de contratação<strong>{metrics.hireRate.toFixed(0)}%</strong></span></div><div><span className="connect-symbol">C</span><span>Connects gastos<strong>{metrics.connects}</strong></span></div><div><span className="money-symbol">$</span><span>Projetos conquistados<strong>US$ {metrics.wonValue.toFixed(2)}</strong></span></div></section>
    <section className="table-toolbar card"><div className="search-field"><Search size={18} /><input placeholder="Pesquisar propostas..." value={search} onChange={(e) => setSearch(e.target.value)} /></div><select aria-label="Filtrar por status" value={status} onChange={(e) => setStatus(e.target.value)}><option value="">Todos os status</option>{statuses.map((item) => <option key={item}>{item}</option>)}</select><select aria-label="Filtrar por plataforma" value={platform} onChange={(e) => setPlatform(e.target.value)}><option value="">Todas as plataformas</option>{platforms.map((item) => <option key={item}>{item}</option>)}</select><button className="button ghost" onClick={() => setSortDesc((value) => !value)}><ArrowUpDown size={16} /> Data</button></section>
    {list.length === 0 ? <div className="empty-state"><BriefcaseBusiness size={38} /><h3>{data.proposals.length ? 'Nenhuma proposta encontrada' : 'Sua próxima oportunidade começa aqui'}</h3><p>{data.proposals.length ? 'Altere os filtros para encontrar outro registro.' : 'Registre propostas para acompanhar respostas, entrevistas e contratos.'}</p><button className="button primary" onClick={() => setEditing(emptyProposal())}><Plus size={17} /> Adicionar proposta</button></div> : <div className="responsive-table card"><table><thead><tr><th>Projeto</th><th>Plataforma</th><th>Data</th><th>Orçamento</th><th>Status</th><th>Próximo passo</th><th aria-label="Ações" /></tr></thead><tbody>{list.map((item) => { const follow = item.followUpDate && item.followUpDate <= dateNow() && !['Contratado', 'Recusada', 'Ignorada'].includes(item.status); return <tr key={item.id} className={follow ? 'needs-followup' : ''} onDoubleClick={() => setEditing(item)}><td><button className="table-main" onClick={() => setEditing(item)}>{item.projectName}<small>{item.clientName || 'Cliente não informado'}</small></button></td><td>{item.platform}</td><td>{item.date.split('-').reverse().join('/')}</td><td>US$ {item.budgetUsd.toFixed(2)}</td><td><span className={`status-pill proposal-${item.status.toLowerCase()}`}>{item.status}</span></td><td>{follow && <span className="follow-badge">Acompanhar</span>}{item.nextStep || '—'}</td><td><div className="table-actions">{item.url && <a href={item.url} target="_blank" rel="noreferrer" className="icon-button" aria-label="Abrir anúncio"><ExternalLink size={16} /></a>}<button className="icon-button" onClick={() => duplicate(item)} aria-label="Duplicar proposta"><Copy size={16} /></button><button className="icon-button danger-icon" onClick={() => data.settings.confirmBeforeDelete ? setDeleting(item) : remove('proposals', item.id)} aria-label="Excluir proposta"><Trash2 size={16} /></button></div></td></tr> })}</tbody></table></div>}
    <button className="floating-add" onClick={() => setEditing(emptyProposal())} aria-label="Adicionar proposta"><Plus /></button>
    {editing && <Modal title={data.proposals.some((item) => item.id === editing.id) ? 'Editar proposta' : 'Nova proposta'} onClose={() => setEditing(null)} size="large"><ProposalForm initial={editing} onClose={() => setEditing(null)} /></Modal>}
    {deleting && <ConfirmModal title="Excluir proposta?" message={`A proposta “${deleting.projectName}” será removida permanentemente.`} danger onClose={() => setDeleting(null)} onConfirm={() => { remove('proposals', deleting.id); notify('Proposta excluída.') }} />}
  </div>
}
