import { CheckCircle2, Plus, Sparkles, Trash2, Wrench } from 'lucide-react'
import { useState, type FormEvent } from 'react'
import { ConfirmModal, Modal } from '../components/Modal'
import { useApp } from '../context/AppContext'
import { deletionBlockReason } from '../data/domain'
import type { FreelanceService, ServiceStatus } from '../types'

const emptyService = (): FreelanceService => ({ id: crypto.randomUUID(), name: '', startingPriceUsd: 0, estimatedTime: '', scope: '', included: '', excluded: '', status: 'Rascunho' })
function ServiceForm({ initial, onClose }: { initial: FreelanceService; onClose: () => void }) {
  const { upsert, notify } = useApp(); const [form, setForm] = useState(initial); const set = <K extends keyof FreelanceService>(key: K, value: FreelanceService[K]) => setForm((current) => ({ ...current, [key]: value }))
  const submit = (event: FormEvent) => { event.preventDefault(); upsert('services', form); notify('Serviço salvo.', 'success'); onClose() }
  return <form className="form-grid" onSubmit={submit}><label className="wide">Nome *<input required value={form.name} onChange={(e) => set('name', e.target.value)} /></label><label>Preço inicial (US$)<input type="number" min="0" value={form.startingPriceUsd} onChange={(e) => set('startingPriceUsd', Number(e.target.value))} /></label><label>Tempo estimado<input placeholder="Ex.: 2 a 4 horas" value={form.estimatedTime} onChange={(e) => set('estimatedTime', e.target.value)} /></label><label className="wide">Escopo<textarea value={form.scope} onChange={(e) => set('scope', e.target.value)} /></label><label className="wide">O que está incluído<textarea value={form.included} onChange={(e) => set('included', e.target.value)} /></label><label className="wide">O que não está incluído<textarea value={form.excluded} onChange={(e) => set('excluded', e.target.value)} /></label><label>Status<select value={form.status} onChange={(e) => set('status', e.target.value as ServiceStatus)}><option>Rascunho</option><option>Pronto</option><option>Publicado</option><option>Vendido</option></select></label><div className="form-actions wide"><button type="button" className="button secondary" onClick={onClose}>Cancelar</button><button className="button primary">Salvar serviço</button></div></form>
}

export function ServicesPage() {
  const { data, remove, notify } = useApp(); const [editing, setEditing] = useState<FreelanceService | null>(null); const [deleting, setDeleting] = useState<FreelanceService | null>(null)
  const requestDelete = (item: FreelanceService) => { if (deletionBlockReason(data, 'services', item.id)) { notify('Não é possível excluir: há uma proposta relacionada.', 'error'); return } if (data.settings.confirmBeforeDelete) setDeleting(item); else remove('services', item.id) }
  return <div><section className="page-intro"><div><span className="kicker">Seu catálogo</span><h2>Serviços</h2><p>Ofertas claras tornam propostas mais rápidas e escopos mais seguros.</p></div><button className="button primary" onClick={() => setEditing(emptyService())}><Plus size={17} /> Novo serviço</button></section><div className="services-grid">{data.services.map((item, index) => <article className="card service-card" key={item.id}><div className="service-top"><div className="service-number">0{index + 1}</div><span className={`status-pill service-${item.status.toLowerCase()}`}>{item.status}</span></div><div className="service-icon"><Wrench size={22} /></div><h3>{item.name}</h3><p>{item.scope}</p><div className="service-price"><span>A partir de</span><strong>US$ {item.startingPriceUsd.toFixed(0)}</strong><small>{item.estimatedTime}</small></div><div className="scope-block include"><strong><CheckCircle2 size={16} /> Inclui</strong><p>{item.included}</p></div><div className="scope-block exclude"><strong>Limites do escopo</strong><p>{item.excluded}</p></div><footer><button className="button secondary" onClick={() => setEditing(item)}>Editar serviço</button><button className="icon-button danger-icon" onClick={() => requestDelete(item)} aria-label="Excluir serviço"><Trash2 size={17} /></button></footer></article>)}<button className="add-service-card" onClick={() => setEditing(emptyService())}><Sparkles size={28} /><strong>Criar nova oferta</strong><span>Transforme outra habilidade em um serviço claro.</span></button></div>{editing && <Modal title={data.services.some((item) => item.id === editing.id) ? 'Editar serviço' : 'Novo serviço'} onClose={() => setEditing(null)}><ServiceForm initial={editing} onClose={() => setEditing(null)} /></Modal>}{deleting && <ConfirmModal title="Excluir serviço?" message={`O serviço “${deleting.name}” será removido.`} danger onClose={() => setDeleting(null)} onConfirm={() => { remove('services', deleting.id); notify('Serviço excluído.') }} />}</div>
}
