import { AlertTriangle, Bell, DatabaseBackup, Download, Moon, RefreshCcw, Save, Sun, Trash2, Upload } from 'lucide-react'
import { useRef, useState, type FormEvent } from 'react'
import { ConfirmModal, Modal } from '../components/Modal'
import { useApp } from '../context/AppContext'
import { createDefaultData } from '../data/defaults'
import { exportBackup, parseBackup, resetRoadmap } from '../services/storage'
import type { Settings } from '../types'

export function SettingsPage() {
  const { data, lastSavedAt, updateSettings, replaceData, notify } = useApp()
  const [form, setForm] = useState<Settings>(data.settings)
  const [confirmReset, setConfirmReset] = useState<'roadmap' | 'all' | null>(null)
  const [deleteText, setDeleteText] = useState('')
  const fileRef = useRef<HTMLInputElement>(null)
  const set = <K extends keyof Settings>(key: K, value: Settings[K]) => setForm((current) => ({ ...current, [key]: value }))
  const save = (event: FormEvent) => { event.preventDefault(); updateSettings(form); notify('Configurações salvas.', 'success') }
  const download = () => {
    const blob = new Blob([JSON.stringify(exportBackup(data), null, 2)], { type: 'application/json' })
    const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = `freelance-focus-backup-${new Date().toISOString().slice(0, 10)}.json`; anchor.click(); URL.revokeObjectURL(url); notify('Backup exportado.', 'success')
  }
  const importFile = async (file: File) => { try { const imported = parseBackup(await file.text()); replaceData(imported); setForm(imported.settings); notify('Backup importado com sucesso.', 'success') } catch (error) { notify(error instanceof Error ? error.message : 'Não foi possível importar o arquivo.', 'error') } }
  return <div><section className="page-intro"><div><span className="kicker">Personalização e dados</span><h2>Configurações</h2><p>Ajuste seu ciclo e mantenha uma cópia segura dos dados locais.</p></div><span className="save-status"><Save size={15} /> Salvo {new Intl.DateTimeFormat('pt-BR', { dateStyle: 'short', timeStyle: 'short' }).format(new Date(lastSavedAt))}</span></section>
    <form onSubmit={save} className="settings-layout"><section className="card settings-section"><header><div className="settings-icon"><Sun size={19} /></div><div><h3>Perfil e metas</h3><p>Informações usadas nos resumos do painel.</p></div></header><div className="form-grid"><label>Seu nome<input value={form.userName} onChange={(e) => set('userName', e.target.value)} placeholder="Como quer ser chamado?" /></label><label>Data inicial do roadmap<input type="date" value={form.roadmapStartDate} onChange={(e) => set('roadmapStartDate', e.target.value)} /></label><label>Meta semanal em dólar<input type="number" min="0" value={form.weeklyGoalUsd} onChange={(e) => set('weeklyGoalUsd', Number(e.target.value))} /></label><label>Horas semanais disponíveis<input type="number" min="1" value={form.weeklyHours} onChange={(e) => set('weeklyHours', Number(e.target.value))} /></label><label>Moeda principal<select value={form.primaryCurrency} onChange={(e) => set('primaryCurrency', e.target.value as 'USD' | 'BRL')}><option value="USD">Dólar (USD)</option><option value="BRL">Real (BRL)</option></select></label><label>Cotação padrão do dólar<input type="number" min="0" step="0.01" value={form.defaultExchangeRate} onChange={(e) => set('defaultExchangeRate', Number(e.target.value))} /></label></div><p className="inline-note"><RefreshCcw size={15} /> Alterar a data inicial recalcula as datas sem apagar status ou observações.</p></section>
      <section className="card settings-section"><header><div className="settings-icon"><Moon size={19} /></div><div><h3>Aparência e comportamento</h3><p>Preferências salvas neste navegador.</p></div></header><div className="theme-options">{(['light', 'dark', 'system'] as const).map((theme) => <button type="button" key={theme} className={form.theme === theme ? 'active' : ''} aria-pressed={form.theme === theme} onClick={() => set('theme', theme)}>{theme === 'light' ? <Sun /> : theme === 'dark' ? <Moon /> : <span className="system-theme">A</span>}<span>{theme === 'light' ? 'Claro' : theme === 'dark' ? 'Escuro' : 'Sistema'}</span></button>)}</div><label className="switch-row"><span><Bell size={18} /><span><strong>Notificações internas</strong><small>Feedback de ações e lembretes no painel.</small></span></span><input type="checkbox" checked={form.notificationsEnabled} onChange={(e) => set('notificationsEnabled', e.target.checked)} /></label><label className="switch-row"><span><AlertTriangle size={18} /><span><strong>Confirmar antes de excluir</strong><small>Evita remoções acidentais de registros.</small></span></span><input type="checkbox" checked={form.confirmBeforeDelete} onChange={(e) => set('confirmBeforeDelete', e.target.checked)} /></label></section><div className="settings-save"><button className="button primary"><Save size={17} /> Salvar configurações</button></div></form>
    <section className="card settings-section data-section"><header><div className="settings-icon"><DatabaseBackup size={19} /></div><div><h3>Backup e restauração</h3><p>Todos os dados ficam somente neste dispositivo.</p></div></header><div className="data-actions"><button className="data-action" onClick={download}><Download /><span><strong>Exportar backup</strong><small>Baixar todos os dados em JSON.</small></span></button><button className="data-action" onClick={() => fileRef.current?.click()}><Upload /><span><strong>Importar backup</strong><small>Validar e restaurar um arquivo JSON.</small></span></button><input ref={fileRef} type="file" accept="application/json,.json" hidden onChange={(e) => e.target.files?.[0] && importFile(e.target.files[0])} /><button className="data-action" onClick={() => setConfirmReset('roadmap')}><RefreshCcw /><span><strong>Restaurar roadmap</strong><small>Recriar apenas as 90 metas originais.</small></span></button><button className="data-action destructive" onClick={() => { setDeleteText(''); setConfirmReset('all') }}><Trash2 /><span><strong>Apagar todos os dados</strong><small>Remover progresso e registros locais.</small></span></button></div></section>
    {confirmReset === 'roadmap' && <ConfirmModal title="Restaurar roadmap original?" message="Status, observações e reagendamentos das 90 tarefas serão substituídos. Propostas, contratos e serviços permanecem." danger onClose={() => setConfirmReset(null)} onConfirm={() => { replaceData(resetRoadmap(data)); notify('Roadmap restaurado.') }} />}
    {confirmReset === 'all' && <Modal title="Apagar todos os dados?" onClose={() => setConfirmReset(null)}><div className="strong-confirm"><AlertTriangle /><p>Esta ação remove todo o seu progresso, propostas, contratos e serviços personalizados. Digite <strong>APAGAR</strong> para confirmar.</p><input autoFocus aria-label="Digite APAGAR para confirmar" value={deleteText} onChange={(e) => setDeleteText(e.target.value)} placeholder="APAGAR" /><div className="form-actions"><button className="button secondary" onClick={() => setConfirmReset(null)}>Cancelar</button><button className="button danger" disabled={deleteText !== 'APAGAR'} onClick={() => { const defaults = createDefaultData(); replaceData(defaults); setForm(defaults.settings); setConfirmReset(null); notify('Todos os dados foram apagados.') }}>Apagar permanentemente</button></div></div></Modal>}
  </div>
}
